GENERAL:
  task: train  # train, test
  manual_seed: 456
  model_dir: model/hais/hais.py
  dataset_dir: data/scannetv2_inst.py

DATA:
  data_root: dataset
  dataset: s3dis
  filename_suffix: _inst_nostuff.pth
  train_areas: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
  test_area: 'Area_5'
  train_repeats: 5

  semantic_classes: 13
  classes: 13
  ignore_label: -100
  class_numpoint_mean: [1823, 7457, 6189, 7424, 34229, 1724, 5439,
                        6016, 39796, 5279, 5092, 12210, 10225]

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50 -> voxel_size 0.02m
  batch_size: 1
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: hais
  width: 32
  block_residual: True
  block_reps: 2
  use_coords: True

TRAIN:
  epochs: 30
  train_workers: 8 # data loader workers
  optim: Adam # Adam or SGD
  lr: 0.001
  step_epoch: 0
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 4  # also eval_freq
  loss_weight: [1.0, 1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, cls_loss, mask_loss, score_loss
  fg_thresh: 1.
  bg_thresh: 0.
  score_scale: 50 # the minimal voxel size is 2cm
  score_fullscale: 20  
  score_mode: 4 # mean
  pretrain_path: 
  pretrain_module: ['input_conv', 'unet', 'output_layer',
                      'semantic_linear', 'offset_linear',
                     'intra_ins_unet', 'intra_ins_outputlayer', 
                     'score_linear', 'mask_linear']

                            

  fix_module: [] 


  point_aggr_radius: 0.04
  cluster_shift_meanActive: 300
  prepare_epochs: 0
  
  cal_iou_based_on_mask: True
  cal_iou_based_on_mask_start_epoch: 5

  use_mask_filter_score_feature: True
  use_mask_filter_score_feature_start_epoch: 5
  mask_filter_score_feature_thre: 0.5
  
  using_set_aggr_in_training: False
  using_set_aggr_in_testing: True

  max_proposal_num: 200

TEST:
  split: val
  test_epoch: 100
  test_workers: 16
  test_seed: 567

  using_NMS: False
  TEST_NMS_THRESH: 0.3
  TEST_SCORE_THRESH: 0.09
  TEST_NPOINT_THRESH: 100

  eval: True
  save_semantic: False
  save_pt_offsets: False
  save_instance: False

  test_mask_score_thre: -0.5 # bias fg << bg
